Create Classes Associations - School Library Project
ouasamine/school-library pull request #3
Opened 2022-12-22 22:41 UTC by ouasamine

## Overview
In this part, I created additional classes (Book, Rentals, Classroom) and created relationships between different classes.

## Workflow
- [Created a `Classroom` class](https://github.com/ouasamine/school-library/commit/11afb84df8bc4b5e713f7b706e15bf76bf09792b)
- [Created a relationship between `Classroom` and `Student` classes](https://github.com/ouasamine/school-library/commit/c2ce1b8e9271891334d40c1cf18dbed29fd3ea75)
- [Created a `Book` class](https://github.com/ouasamine/school-library/commit/c932551322fc8ea7040ed7b500e0f933ff384b65)
- [Created a `Rental` class](https://github.com/ouasamine/school-library/commit/5070f53f526c2aa150199f84cd6664c001e517f1)
- [Created a many-to-many relationship between `Book` and `Person` classes through Rental class](https://github.com/ouasamine/school-library/commit/18035e133af8a7612138dede9b36858a0a32a849)

2022-12-22 23:56 UTC, codecaiine requested changes
Hi @ouasamine , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good class relationship setup :heavy_check_mark: 
- No rubocop errors :heavy_check_mark: 
- Good use of gitflow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 23:56 UTC, codecaiine commented on classroom.rb
> +
- [ ] Good job so far :clap:  I would like to recommend adding a getter for student, an instance variable has `attr_reader` to make you able to call it and read it in your add_student method. Please fix in order to make your app works as expected :+1: 

````
def add_rental(person, date)
  Rental.new(date, person, self)
end
```

2022-12-22 23:56 UTC, codecaiine commented on student.rb
- [ ] I would like to recommend you create a correct method that serves as the 'belongs-to' side a student belongs to a classroom. Please follow the link to that [article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships) that will help you to implement:+1: It is very important to make it in order to make your project work as expected :+1:

2022-12-22 23:56 UTC, codecaiine commented on book.rb
> +  attr_accessor :title, :author
- [ ] Good job so far :clap:  I would like to recommend adding a setter and getter for rentals, an instance variable has `attr_accessor` as required for this project. Please fix in order to make your app works as expected :+1:

2022-12-22 23:56 UTC, codecaiine commented on book.rb
> +  end
- [ ] I would like to recommend you implement the add_rental method using the same pattern as you have taken in the person class, but in this case `person`  and `date` are the parameters. Please fix it in order to make your app work as expected :+1:

2022-12-22 23:56 UTC, codecaiine commented on person.rb
> +  attr_reader :id
- [ ] I would like to recommend you make sure that all your instance variables have `attr_accessor` since there are both getter and setter.  attr_reader defines only getter don't forget setter and getters for @rentals.  Please fix it to make your code work as expected :+1:

2022-12-22 23:56 UTC, codecaiine commented on person.rb
> +  end
- [ ] I would like to recommend you have `book` and `date` as parameters and note that The person itself should be sent as a parameter to create the new rental achieving the 'has-many' association :+1:

2022-12-23 08:52 UTC, medaminedev66 reviewed
Hello @ouasamine 👋,

_This is an additional review as a result of the second opinion request._

Following the project requirements, you are expected to create the associations between Classes, which means that many methods should be implemented to achieve that goal. I tried to explain the changes requested by the previous reviewer in more detail. Kindly take a look at the comments I left below the previous reviewer's comments.

Keep rocking 🚀!

2022-12-23 08:52 UTC, medaminedev66 commented on book.rb
> +  attr_accessor :title, :author
According to many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental:
- A book has many rentals: and that means that setters and getters for the instance variable @rental (defined in line 7) should be present in the Book class so that you can access this variable in the Rental class.

2022-12-23 08:52 UTC, medaminedev66 commented on book.rb
> +  end
The Code Reviewer means that the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. Kindly check out the example below:
```ruby
def add_rental(person, date)
    Rental.new(date, self, person)
 end
```

2022-12-23 08:52 UTC, medaminedev66 commented on classroom.rb
> +
According to `has-many` / `belongs-to` relationships between `Clasroom` and `Student`, getters and setters for the instance variable @students should be present in Classroom class so that you can access that variable in Student class (Take a look at line 7 in student.rb file which I will correct it in the comment below)

2022-12-23 08:52 UTC, medaminedev66 commented on student.rb
According to `has-many` / `belongs-to` relationships between `Classroom` and `Student`, when setting the classroom for a student it also adds it to the classrooms' students and that means a method that serves as the 'belongs-to' side (a student belongs to a classroom) should be present in Classroom class. I recommend removing line 7 and creating a method instead. Take a look at the example below:
```ruby
def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2022-12-23 08:52 UTC, medaminedev66 commented on person.rb
> +  attr_reader :id
According to many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental:
- A person has many rentals: and that means that setters and getters for the instance variable @rental (defined in line 16) should be present in the Person class so that you can access this variable in the Rental class.

2022-12-23 08:52 UTC, medaminedev66 commented on person.rb
> +  end
The Code Reviewer means that the person itself should be sent as a parameter to create the new rental achieving the 'has-many' association. Kindly check out the example below:
```ruby
 def add_rental(book, date)
    Rental.new(date, book, self)
  end
```

2022-12-23 09:26 UTC, BertrandConxy requested changes
Hi @ouasamine, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions
- good PR


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 09:26 UTC, BertrandConxy commented on student.rb
> +    classroom.students << self
- [ ] It is important to note that a student should not be added to a classroom if she/he has already been added 💡 That is the reason why the previous code reviewer shared code with a line that looks like the below 👇 
```ruby
def classroom=(classroom)
 ...
 classroom.students.push(self) unless classroom.students.include?(self)
end
```
As you can see, there is an `unless` statement to make sure that a student is not added if she/he is already present 😉 

Please make sure that you add that unless statement also in your code. That means your method will looks like the following 👇 
```ruby
def classroom=(classroom)
  @classroom = classroom
  classroom.students << self unless classroom.students.include?(self)
end
```

2022-12-23 09:35 UTC, m05e5 approved these changes
Hi @ouasamine   , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Descriptive PR 
✔️ your linters are all ok

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 09:36 UTC, merged